# Generated by Django 4.2.27 on 2026-02-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousDetectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('interval', models.IntegerField(default=5, verbose_name='检测间隔(秒)')),
                ('target_devices', models.JSONField(blank=True, default=list, verbose_name='目标设备ID列表')),
                ('total_detections', models.IntegerField(default=0, verbose_name='累计检测次数')),
                ('total_anomalies', models.IntegerField(default=0, verbose_name='累计异常次数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '持续检测配置',
                'verbose_name_plural': '持续检测配置',
                'db_table': 'continuous_detection_config',
            },
        ),
    ]
