# Generated by Django 4.2.22 on 2026-05-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_continuousdetectionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionrecord',
            name='feedback_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='反馈时间'),
        ),
        migrations.AddField(
            model_name='detectionrecord',
            name='feedback_label',
            field=models.BooleanField(blank=True, db_index=True, help_text='None=未反馈, True=确认异常, False=纠正为正常(误报)', null=True, verbose_name='用户反馈标签'),
        ),
        migrations.AlterField(
            model_name='continuousdetectionconfig',
            name='interval',
            field=models.IntegerField(default=60, verbose_name='检测间隔(秒)'),
        ),
    ]
