# Generated by Django 4.2.22 on 2026-05-24 08:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='模型ID')),
                ('model_name', models.CharField(max_length=128, verbose_name='模型名称')),
                ('model_type', models.CharField(choices=[('isolation_forest', '孤立森林'), ('autoencoder', '自编码器'), ('knn', 'K近邻'), ('svm', '支持向量机'), ('ensemble', '集成模型'), ('lstm', 'LSTM'), ('gru', 'GRU')], db_index=True, max_length=32, verbose_name='模型类型')),
                ('version', models.CharField(default='v1.0', max_length=32, verbose_name='版本号')),
                ('status', models.CharField(choices=[('training', '训练中'), ('ready', '就绪'), ('deployed', '已部署'), ('archived', '已归档'), ('failed', '训练失败')], db_index=True, default='training', max_length=20, verbose_name='状态')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='是否当前激活模型')),
                ('training_dataset', models.CharField(blank=True, max_length=256, null=True, verbose_name='训练数据集')),
                ('training_samples', models.IntegerField(default=0, verbose_name='训练样本数')),
                ('validation_samples', models.IntegerField(default=0, verbose_name='验证样本数')),
                ('f1_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='F1分数')),
                ('precision', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='精确率')),
                ('recall', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='召回率')),
                ('accuracy', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='准确率')),
                ('auc_roc', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='AUC-ROC')),
                ('false_positive_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='误报率')),
                ('false_negative_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='漏报率')),
                ('inference_time_ms', models.FloatField(default=0.0, verbose_name='推理时间(ms)')),
                ('memory_usage_mb', models.FloatField(default=0.0, verbose_name='内存占用(MB)')),
                ('model_size_mb', models.FloatField(default=0.0, verbose_name='模型大小(MB)')),
                ('model_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='模型文件路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('trained_at', models.DateTimeField(blank=True, null=True, verbose_name='训练完成时间')),
            ],
            options={
                'verbose_name': '算法模型',
                'verbose_name_plural': '算法模型',
                'db_table': 'algorithm_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='任务ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='进度(%)')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='训练配置')),
                ('result_metrics', models.JSONField(blank=True, default=dict, verbose_name='结果指标')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('training_log', models.TextField(blank=True, null=True, verbose_name='训练日志')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_tasks', to='algorithm.algorithmmodel', verbose_name='关联模型')),
            ],
            options={
                'verbose_name': '训练任务',
                'verbose_name_plural': '训练任务',
                'db_table': 'algorithm_training_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureImportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(db_index=True, max_length=128, verbose_name='特征名称')),
                ('importance_score', models.FloatField(default=0.0, verbose_name='重要性分数')),
                ('rank', models.IntegerField(db_index=True, verbose_name='排名')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_importances', to='algorithm.algorithmmodel', verbose_name='关联模型')),
            ],
            options={
                'verbose_name': '特征重要性',
                'verbose_name_plural': '特征重要性',
                'db_table': 'algorithm_feature_importance',
                'ordering': ['model', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='评估指标')),
                ('evaluation_dataset', models.CharField(blank=True, max_length=256, null=True, verbose_name='评估数据集')),
                ('evaluation_samples', models.IntegerField(default=0, verbose_name='评估样本数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='algorithm.algorithmmodel', verbose_name='关联模型')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='algorithm.trainingtask', verbose_name='关联训练任务')),
            ],
            options={
                'verbose_name': '评估结果',
                'verbose_name_plural': '评估结果',
                'db_table': 'algorithm_evaluation_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='algorithmmodel',
            index=models.Index(fields=['model_type', 'status'], name='algorithm_m_model_t_ecd449_idx'),
        ),
        migrations.AddIndex(
            model_name='algorithmmodel',
            index=models.Index(fields=['is_active', 'status'], name='algorithm_m_is_acti_fcc7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingtask',
            index=models.Index(fields=['status', 'created_at'], name='algorithm_t_status_853ada_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featureimportance',
            unique_together={('model', 'feature_name')},
        ),
    ]
