# Generated by Django 4.2.22 on 2026-05-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmmodel',
            name='training_params',
            field=models.JSONField(blank=True, default=dict, help_text='训练参数字典，用于判断是否为相同配置的模型', verbose_name='训练参数'),
        ),
    ]
