# Generated by Django 4.2.27 on 2025-12-25 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_score_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='评分更新时间'),
        ),
        migrations.AddField(
            model_name='device',
            name='security_score',
            field=models.FloatField(default=100.0, verbose_name='安全评分'),
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='分组名称')),
                ('description', models.TextField(blank=True, verbose_name='分组描述')),
                ('icon', models.CharField(blank=True, default='folder', max_length=64, verbose_name='图标')),
                ('color', models.CharField(default='#1890ff', max_length=7, verbose_name='颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='devices.devicegroup')),
            ],
            options={
                'verbose_name': '设备分组',
                'verbose_name_plural': '设备分组',
                'db_table': 'device_groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='devices', to='devices.devicegroup', verbose_name='所属分组'),
        ),
    ]
