# Generated by Django 4.2.22 on 2026-05-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_last_score_update_device_security_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('warning', '告警')], default='online', max_length=20, verbose_name='状态'),
        ),
    ]
