# Generated by Django 4.2.22 on 2026-05-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_update_device_default_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('camera', '智能摄像头'), ('door_lock', '智能门锁'), ('sensor', '传感器'), ('gateway', '网关'), ('switch', '智能开关'), ('robot', '扫地机器人'), ('lock', '门锁'), ('curtain', '窗帘电机'), ('light', '智能灯泡'), ('speaker', '智能音箱'), ('ac_companion', '空调伴侣'), ('purifier', '空气净化器'), ('alarm', '烟雾报警器'), ('other', '其他')], default='other', max_length=20, verbose_name='设备类型'),
        ),
    ]
