# Generated by Django 4.2.22 on 2026-08-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0003_add_feedback_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64, verbose_name='Device ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('critical', 'Critical')], db_index=True, default='warning', max_length=10, verbose_name='Level')),
                ('attack_type', models.CharField(db_index=True, max_length=20, verbose_name='Attack type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Confidence')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='pending', max_length=10, verbose_name='Status')),
                ('handling_note', models.TextField(blank=True, verbose_name='Handling note')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Handled at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('detection_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='detection.detectionrecord', verbose_name='Detection record')),
            ],
            options={
                'verbose_name': 'Alert log',
                'verbose_name_plural': 'Alert logs',
                'db_table': 'alert_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['status', 'created_at'], name='alert_logs_status__cc1194_idx'),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['device_id', 'created_at'], name='alert_logs_device__103051_idx'),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['level', 'created_at'], name='alert_logs_level_80b005_idx'),
        ),
    ]
