# Generated by Django 4.2.27 on 2026-02-14 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='用户名')),
                ('action', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('create', '创建'), ('update', '更新'), ('delete', '删除'), ('view', '查看'), ('export', '导出'), ('import', '导入'), ('start', '启动'), ('stop', '停止'), ('config', '配置'), ('other', '其他')], max_length=20, verbose_name='操作类型')),
                ('resource_type', models.CharField(choices=[('user', '用户'), ('device', '设备'), ('device_group', '设备分组'), ('detection_task', '检测任务'), ('detection_result', '检测结果'), ('system', '系统'), ('other', '其他')], max_length=30, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='资源ID')),
                ('resource_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='资源名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='操作描述')),
                ('request_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='请求路径')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='请求方法')),
                ('request_data', models.TextField(blank=True, null=True, verbose_name='请求数据')),
                ('response_code', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='变更前数据')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='变更后数据')),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], default='success', max_length=20, verbose_name='操作结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='会话ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx'), models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx'), models.Index(fields=['resource_type', 'created_at'], name='audit_logs_resourc_b47635_idx'), models.Index(fields=['result', 'created_at'], name='audit_logs_result_ef0483_idx')],
            },
        ),
    ]
